pipeline {
    agent any

    stages {
        stage('Clonar o repositorio') {
            steps {
                git branch 'main', url: 'https://github.com/JoaoPedromart573/teste-api-ebac.git'
            }
        }
    stage('Instalar dependencias') {
        steps{
            sh 'npm install'
        }
    }
    stage('Executtar Teste') {
        steps {
            sh 'NO_COLOR=1 npm run cy:run'
        }
    }
 }
}